### Chapters 7 to 13: Matrices

#### Chapter 7: Vectors and Vector Arithmetic
A vector is a tuple of one or more values called scalars.

$ v = (v_1, v_2, v_3) \quad or \quad  v =  {\begin{pmatrix}
   v_1 \\
   v_2 \\
   v_3 \\    
 \end{pmatrix} } $




In [7]:
# Defining a Vector
from numpy import array

# create a vector
v = array([1, 2, 3])
print(v)
# define first vector
a = array([1, 2, 3])
print(a)

# Vector arithmetic

# vector addition
c = a + v
print(c)

# vector subtraction
c = a - v
print(c)

# vector multiplication
c = a * v
print(c)

# vector division
c = a / v
print(c)

# vector dot product
c = a.dot(v)
print(c)

# vector-scalar multiplication
s = 0.5
c = s * a
print(c)


[1 2 3]
[1 2 3]
[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
14
[0.5 1.  1.5]


#### Chapter 8: Vector Norms
The length of a vector is a nonnegative number that describes the extent of the
vector in space, and is sometimes referred to as the vector's magnitude or the norm.

- $L^1$ Norm

    $L^1(v) \quad = \quad \lVert v \rVert_1 \quad = \quad |a_1| + |a_2| + ... + |a_n| $

- $L^2$ Norm

    $L^2(v) \quad = \quad \lVert v \rVert_2 \quad = \quad \sqrt{a_1^2 + a_2^2 + ... + a_n^2} $
    
- $L^{inf}$ Norm

    $L^{inf}(v) \quad = \quad \lVert v \rVert_{inf} = $ max $a_1,a_2,a_3$
    
By far, the L2 norm is more commonly used than other vector norms in machine learning.

In [17]:
# vector norms
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate L1 norm
l1 = norm(a, 1)
print(l1)

# calculate L2 norm
l2 = norm(a)
print(l2)

# calculate vector max norm
from math import inf
maxnorm = norm(a, inf)
print(maxnorm)


[1 2 3]
6.0
3.7416573867739413
3.0


#### Chapter 9: Matrices and Matrix Arithmetic
A matrix is a two-dimensional array of scalars with one or more columns and one or more rows.

$A =  {\begin{pmatrix}
   a_{1,1} & a_{1,2} \\
   a_{2,1} & a_{2,2} \\
   a_{3,1} & a_{3,2} \\    
 \end{pmatrix} } $


In [11]:
from numpy import array
# create matrix
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[0.5, 0.5, 0.5],
[0.5, 0.5, 0.5]])
print(B)

# matrix addition
C = A + B
print(C)

# matrix subtraction
C = A - B
print(C)

# matrix Hadamard product
C = A * B
print(C)

# matrix division
C = A / B
print(C)

# matrix dot product
A2 = array([
[1, 2],
[3, 4],
[5, 6]])
print(A2)
# define second matrix
B2 = array([
[1, 2],
[3, 4]])
print(B2)
# multiply matrices
C = A2.dot(B2)
print(C)
# multiply matrices with @ operator
D = A2 @ B2
print(D)

# matrix-vector multiplication
# define vector
v = array([0.5, 0.5])
print(v)
# multiply
C = A2.dot(v)
print(C)

# matrix-scalar multiplication
b = 0.5
print(b)
# multiply
C = A2 * b
print(C)


[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]
[0.5 0.5]
[1.5 3.5 5.5]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


#### Chapter 10: Types of Matrices
- Square Matrix:

    $n = m$
    
- Symmetric Matrix:

    [M] top-right triangle is the same as the bottom-left triangle. $M = M^T$
    
- Triangular Matrix:

    all values in the upper-right[U] or lower-left[L] of the matrix with the remaining elements filled with zero values.
    
- Diagonal Matrix:
    
    [D] values outside of the main diagonal have a zero value, where the main diagonal is taken from the top left of the matrix to the bottom right.
    
- Identity Matrix:
    
    [I] square matrix that does not change a vector when multiplied. $AI = IA = A$
     
- Orthogonal Matrix:

    [Q] An orthogonal matrix is a square matrix whose rows are mutually orthonormal and  whose columns are mutually orthonormal.
    Multiplication by an orthogonal matrix preserves lengths. $Q^T · Q = Q · Q^T = I$ and $Q^T = Q^{-1}$

In [15]:
from numpy import array
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)

# triangular matrices
from numpy import tril
from numpy import triu
# Calculate lower triangular matrix
L = tril(M)
print(lower)
# Calculate upper triangular matrix
U = triu(M)
print(upper)

# diagonal matrix
from numpy import diag
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

# identity matrix
from numpy import identity
I = identity(3)
print(I)

# orthogonal matrix
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
[1, 0],
[0, -1]])
print(Q)
# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


#### Chapter 11: Matrix Operations

- Transpose:

    matrix with the number of columns and rows flipped. $ C = A^T $
    
- Inverse:

    $AB = BA = I^n$ then $ B = A^{-1}$ 
    
- Trace:

    $tr(A) = \sum_{i,j} a_{i,j} \quad with \quad i = j$
    
- Determinant:

    $det(A)$ The determinant of a square matrix is a scalar representation of the volume of the matrix.
    
- Rank: 

    $rank(A)$ The rank of a matrix is the estimate of the number of linearly independent rows or columns in a matrix.

In [21]:
# Matrix Operations
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

# transpose matrix
C = A.T
print(C)

# invert matrix
from numpy.linalg import inv
# define matrix
Ai = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
# invert matrix
B = inv(Ai)
print(B)
# multiply A and B
I = Ai.dot(B)
print(I)

# matrix trace
from numpy import trace
# define matrix
At = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(At)
# calculate trace
B = trace(At)
print(B)

# matrix determinant
from numpy.linalg import det
print(At)
# calculate determinant
B = det(At)
print(B)

# matrix rank
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)
# rank 1
M1 = array([
[1,2],
[1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)
# rank 2
M2 = array([
[1,2],
[3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)




[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 2]
 [3 4]
 [5 6]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
15
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16
[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2


#### Chapter 12: Sparse Matrices

A sparse matrix is a matrix that is comprised of mostly zero values. In practice, most large matrices are sparse.

Space Complexity: Very large matrices require a lot of memory, and some very large matrices that we wish to work with are sparse.

Time Complexity: if the matrix contains mostly zero-values, i.e. no data, then performing operations across this matrix may take a long time where the bulk of the computation performed will involve adding or multiplying zero values together.

In practice, most large matrices are sparse.

The solution to representing and working with sparse matrices is to use an alternate data
structure to represent the sparse data.

In [24]:
from numpy import array

# sparse matrix
from scipy.sparse import csr_matrix
# create dense matrix
A = array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])
print(A)
# convert to sparse matrix (CSR method)
S = csr_matrix(A)
print(S)
# reconstruct dense matrix
B = S.todense()
print(B)

# calculate sparsity
from numpy import count_nonzero
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
0.7222222222222222


#### Chapter 13: Tensors and Tensor Arithmetic
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.

In [31]:
from numpy import array

# create tensor
T = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(T.shape)
print(T)

# Tensor Operations 

# tensor addition
C = T + T
print(C)

# tensor subtraction
C = T - T
print(C)

# tensor Hadamard product
C = T * T
print(C)

# tensor division
C = T / T
print(C)

# tensor product
from numpy import tensordot
# define first vector
A = array([1,2])
# define second vector
B = array([3,4])
# calculate tensor product
C = tensordot(A, B, axes=0)
print(C)
C = tensordot(B, A, axes=0)
print(C)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[3 4]
 [6 8]]
[[3 6]
 [4 8]]
