### Chapter 4/5/6 - Numpy

In [1]:
## Arrays
from numpy import array

# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [4]:
# Functions to create arrays

# Empty
from numpy import empty
a = empty([3,3])
print(a)

# Zeros
from numpy import zeros
a = zeros([3,5])
print(a)

# Ones
from numpy import ones
a = ones([5])
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.10665138e-321]
 [6.01346930e-154 2.59338541e+161 4.41622067e+257]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]


In [6]:
# Combine arrays
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)

# create array with vstack
from numpy import vstack
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

# create array with hstack
from numpy import hstack
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]
(6,)


In [8]:
# From list to arrays

# create one-dimensional array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))

# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>
[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [11]:
# Array indexing
# define array
data = array([11, 22, 33, 44, 55])
# index a one-dimensional array
# index data
print(data[0])
print(data[4])
# Specifying integers too large for the bound of the array will cause an error.
# EX: print(data[5])
# negative array indexing
print(data[-1])
print(data[-5])

# index two-dimensional array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,0])
# If we are interested in all items in the rst row, we could leave the second dimension index empty
print(data[0,])

11
55
55
11
11
[11 22]


In [13]:
# Array Slicing
# define array
data = array([11, 22, 33, 44, 55])

# slice a one-dimensional array
print(data[:])
# slice a subset of a one-dimensional array
print(data[0:1])
# negative slicing of a one-dimensional array
print(data[-2:])

# slice a two-dimensional array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# split input and output data
# separate data by column
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

# split train and test data
# separate data by row
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[11 22 33 44 55]
[11]
[44 55]
[[11 22]
 [44 55]
 [77 88]]
[33 66 99]
[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [20]:
# Array reshaping
# define array
data1d = array([11, 22, 33, 44, 55])
# shape of one-dimensional array
print(data1d.shape)

# shape of a two-dimensional array
# list of data
data2d = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data2d = array(data2d)
print(f"(rows,cols) = {data2d.shape}")

# reshape 1D array to 2D
# reshape
data = data1d.reshape((data1d.shape[0], 1))
print(data.shape) 

# reshape 2D array to 3D
# reshape
data = data2d.reshape((data2d.shape[0], data2d.shape[1], 1))
print(data.shape)


(5,)
(rows,cols) = (3, 2)
(5, 1)
(3, 2, 1)


In [24]:
# Chapter 6 - Array Broadcasting
# Broadcasting is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size.
from numpy import array
# define array
a = array([1, 2, 3])
print(a)
# define matrix
A = array([ [1, 2, 3],
            [1, 2, 3]])
print(A)
# define scalar
b = 2
print(b)

# broadcast scalar to one-dimensional array
c = a + b
print(c)

# broadcast scalar to two-dimensional array
C = A + b
print(C)

# broadcast one-dimensional array to two-dimensional array
C = A + a
print(C)

# broadcasting error
b = array([1, 2])
C = A + b
print(C)

[1 2 3]
[[1 2 3]
 [1 2 3]]
2
[3 4 5]
[[3 4 5]
 [3 4 5]]
[[2 4 6]
 [2 4 6]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 