### Chapters 7 to 13: Matrices

#### Chapter 7: Vectors and Vector Arithmetic
A vector is a tuple of one or more values called scalars.

$ v = (v_1, v_2, v_3) \quad or \quad  v =  {\begin{pmatrix}
   v_1 \\
   v_2 \\
   v_3 \\    
 \end{pmatrix} } $




In [7]:
# Defining a Vector
from numpy import array

# create a vector
v = array([1, 2, 3])
print(v)
# define first vector
a = array([1, 2, 3])
print(a)

# Vector arithmetic

# vector addition
c = a + v
print(c)

# vector subtraction
c = a - v
print(c)

# vector multiplication
c = a * v
print(c)

# vector division
c = a / v
print(c)

# vector dot product
c = a.dot(v)
print(c)

# vector-scalar multiplication
s = 0.5
c = s * a
print(c)


[1 2 3]
[1 2 3]
[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
14
[0.5 1.  1.5]


#### Chapter 8: Vector Norms
The length of a vector is a nonnegative number that describes the extent of the
vector in space, and is sometimes referred to as the vector's magnitude or the norm.

- $L^1$ Norm

    $L^1(v) \quad = \quad \lVert v \rVert_1 \quad = \quad |a_1| + |a_2| + ... + |a_n| $

- $L^2$ Norm

    $L^2(v) \quad = \quad \lVert v \rVert_2 \quad = \quad \sqrt{a_1^2 + a_2^2 + ... + a_n^2} $
    
- $L^{inf}$ Norm

    $L^{inf}(v) \quad = \quad \lVert v \rVert_{inf} = $ max $a_1,a_2,a_3$
    
By far, the L2 norm is more commonly used than other vector norms in machine learning.

In [17]:
# vector norms
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate L1 norm
l1 = norm(a, 1)
print(l1)

# calculate L2 norm
l2 = norm(a)
print(l2)

# calculate vector max norm
from math import inf
maxnorm = norm(a, inf)
print(maxnorm)


[1 2 3]
6.0
3.7416573867739413
3.0


#### Chapter 9: Matrices and Matrix Arithmetic